# Solutions for pre-class assignment \#6

For the matrices A and B in the included
file `matrix_1.py`, write two functions that use Gaussian
elimination with partial pivoting to:

1. get the upper-triangular matrix, and
2. calculate the determinant of the matrix using the upper-triangular matrix.  

Do this without destroying the original
matrix by making a copy of the matrix (with `numpy.copy`) and
compare your calculated determinant to the output of the [`scipy.linalg.det`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.linalg.det.html#scipy.linalg.det) routine, as runon the same matrix.  Suggestion: invent your own
  small matrix (perhaps a $3 \times 3$ matrix) to test your routines on so that
  you can verify that it's behaving correctly on a step-by-step basis!


In [2]:
#### FROM matrix_1.py, copied for convenience
import numpy as np
np.set_printoptions(precision=4)

# simple 5x5 array - can calulate this pretty easily.
A = np.array( [[1,-3,2,-1,-2],[-2,2,-1,2,3],[3,-3,-2,1,-1],[1,-2,1,-3,2],[-3,-1,2,1,-3]],dtype='float64')

np.random.seed(8675309)

# much uglier, but should work the same.
B = np.random.rand(6,6)

# note: you can get the shape of an array A (and thus its dimensions) with A.shape(),
# and can print out its first (second) dimension with A.shape[0]  (A.shape[1])


In [22]:
def partial_pivot(array,pivot_row,col):
    
    swap_row = pivot_row
    for i in range(pivot_row,array.shape[0]):
        if np.abs(array[i,col]) > np.abs(array[pivot_row,col]):
            swap_row = i
    
    row1 = np.copy(array[pivot_row,])
    row2 = np.copy(array[swap_row,])

    array[pivot_row,] = row2
    array[swap_row,] = row1

    return swap_row
        
def gauss_elim(array):

    ordering = []

    #print(array)
    if array.shape[0] != array.shape[1]:
        print("careful!  assumption broken!")
        
    for i in range(array.shape[0]):
        
        swap_row = partial_pivot(array,i,i)

        ordering.append(swap_row)
        
        for j in range(i+1,array.shape[0]):

            test_row = np.copy(array[i,])
            test_row *= -float(array[j,i]/array[i,i])
            array[j,] += test_row

    print("rows in order:", ordering)
    
def determinant(array):
    gauss_elim(array)
    det = 1
    for i in range(array.shape[0]):
        det *= array[i,i]
        
    return det

In [23]:
newA = np.copy(A)
#print(newA)
#partial_pivot(newA,0,0)

gauss_elim(newA)

print(newA)

this_det = determinant(newA)

print(this_det)

rows in order: [4, 4, 2, 3, 4]
[[ -3.0000e+00  -1.0000e+00   2.0000e+00   1.0000e+00  -3.0000e+00]
 [  0.0000e+00  -3.3333e+00   2.6667e+00  -6.6667e-01  -3.0000e+00]
 [  0.0000e+00   0.0000e+00  -3.2000e+00   2.8000e+00  -4.0000e-01]
 [  0.0000e+00   0.0000e+00  -2.7756e-17  -2.3750e+00   3.1250e+00]
 [  0.0000e+00   0.0000e+00  -3.5060e-17   0.0000e+00   3.4474e+00]]
rows in order: [0, 1, 2, 3, 4]
262.0


In [16]:
import scipy.linalg

scipy.linalg.det(A)

262.0

In [19]:
newB = np.copy(B)

gauss_elim(newB)

print(newB)

this_det = determinant(newB)

print(this_det)

[[  8.9071e-01   3.9481e-01   3.5511e-01   7.4418e-01   2.3057e-01
    3.5050e-02]
 [  0.0000e+00   3.9092e-01   3.3453e-02  -4.7651e-01   1.9869e-01
    5.0153e-02]
 [  0.0000e+00   5.5511e-17   5.4637e-01   3.8384e-01   6.3543e-01
    6.9629e-01]
 [  0.0000e+00   9.6324e-18   0.0000e+00   9.4511e-01   4.9279e-01
    9.9077e-01]
 [  6.9389e-18  -1.7637e-17   0.0000e+00   0.0000e+00  -1.1224e+00
   -7.9436e-01]
 [  1.4465e-17  -1.1497e-17   0.0000e+00   0.0000e+00   0.0000e+00
    3.7717e-02]]
-0.00761162755247


In [18]:
scipy.linalg.det(B)

0.007611627552473897