In [1]:
import numpy as np

a = np.arange(5)

In [6]:
a.shape

(5,)

In [34]:
b = np.array([[1,2],[3,4]])

d = np.array([[6],[7]])

c = np.zeros([b.shape[0],b.shape[1]+1])

print(d)

[[6]
 [7]]


In [38]:
c[:,0:-1] = b

c[:,-1] 
#print(c)

array([ 0.,  0.])

In [32]:
b

array([[1, 2],
       [3, 4]])